<a href="https://colab.research.google.com/github/nagarvishal/machine-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Create A One-D Array

a = np.array([1,2,3])
print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
#Create A Two-D Array
b = np.array([[1,2,3],[4,5,6]])
print(b,type(b))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [4]:
#Create A Three-D Array
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c,type(c))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]] <class 'numpy.ndarray'>


In [5]:
#Creating A Array of Specific dtype
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# np.arange
np.arange(1,11)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [7]:
# reshape of numpy array - np.arange(1,11).reshape(dim_outmost,rows,columns)
np.arange(1,11).reshape(2,5)
np.arange(1,13).reshape(1,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
# np.once and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# Generate the Random values Array - np.random
np.random.random((3,4))

array([[1.69319709e-01, 8.92319152e-01, 8.54841490e-01, 8.54783295e-01],
       [9.17361594e-01, 5.54771254e-01, 2.94969754e-01, 5.77547760e-01],
       [2.93673409e-01, 6.42804931e-01, 3.56158381e-04, 6.04298671e-01]])

In [11]:
# np.linspace()
np.linspace(-10,10,10)
# np.linspace(-10,10,10,dtype=int)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [13]:
# Array Attributes
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [14]:
# ndim - get the dimentions of numpy array
a1.ndim
a2.ndim
a3.ndim

3

In [15]:
# shape - get the shape of numpy array
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [16]:
# size -  get the number of items in numpy array
a1.size
a2.size
a3.size

8

In [17]:
# itemsize - get the size of numpy array element
a1.itemsize
a2.itemsize
a3.itemsize

8

In [18]:
# dtype - get the datatype of out numpy array element
a1.dtype
a2.dtype
a3.dtype

dtype('int64')

Changing DateType

In [19]:
# astype - Changing datatype of the numpy array
a4 = a3.astype(np.int32)
a4.dtype

dtype('int32')

Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
# Scalar Operations

#Airthmatic Operation
a1 * 2
a1 + 2
a1 - 2
a1 / 2
a1 ** 2
a1 % 2
a1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [22]:
#Relational Operation
a2 > 5
a2 < 5
a2 >= 5
a2 <= 5
a2 == 5
a2 != 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
# Vector Operations

# Airthmatic Operations
a1 + a2
a1 - a2
a1 * a2
a1 / a2
a1 // a2
a1 % a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Array Functions

In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[20., 36., 41.],
       [48., 41., 13.],
       [36., 95., 73.]])

In [25]:
# max,min,sum,prod -> 0=> col,1=>row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis=0)
np.max(a1,axis=1)
np.min(a1,axis=0)
np.min(a1,axis=1)
np.sum(a1,axis=0)
np.sum(a1,axis=1)
np.prod(a1,axis=0)
np.prod(a1,axis=1)


array([ 29520.,  25584., 249660.])

In [26]:
# mean,median,std,var
np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)
np.mean(a1,axis=0)
np.mean(a1,axis=1)
np.median(a1,axis=0)
np.median(a1,axis=1)
np.std(a1,axis=0)
np.std(a1,axis=1)
np.var(a1,axis=0)
np.var(a1,axis=1)

array([ 80.22222222, 228.66666667, 592.66666667])

Trigonometric Functions

In [27]:
#Trigonometric Functions
np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[2.23716094, 7.75047091, 0.1606567 ],
       [1.20012724, 0.1606567 , 0.46302113],
       [7.75047091, 0.93575247, 0.9192864 ]])

DOT Product

In [28]:
# DOT Product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [29]:
# Log and Exponents
np.log(a1)
np.exp(a1)

array([[4.85165195e+08, 4.31123155e+15, 6.39843494e+17],
       [7.01673591e+20, 6.39843494e+17, 4.42413392e+05],
       [4.31123155e+15, 1.81123908e+41, 5.05239363e+31]])

In [30]:
# Rount,Floor,Ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[24., 52.,  1.],
       [89., 20., 61.]])

Indexing And Slicing

In [53]:
# Indexing and Slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [56]:
#Indexing
print(a1[-1],a1[0])
print(a2[1,2],a2[2,3],a2[1,0])
print(a3[1,0,1],a3[0,0,0],a3[1,1,1])

9 0
6 11 4
5 0 7


In [62]:
#Slicing
a1
a1[2:5]
a1[2:5:2]

array([2, 4])

In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3]);
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1,::3])
print(a2[0:2,1:])

[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [76]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
a3[1,:,:]
a3[2,1,0:]
a3[0:,0:,2:]
a3[0::2]
a3[0,1,:]
a3[1,:,1]
a3[2,1:,1:]
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])