<a href="https://colab.research.google.com/github/nagarvishal/machine-learning/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# np.sort - return a sorted copy of an array

In [3]:
a = np.random.randint(1,100,15)
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b


array([[64, 11, 45, 60],
       [65, 59,  8, 77],
       [96, 23, 31, 67],
       [87, 50, 18, 80],
       [57, 91, 33, 41],
       [65, 74, 39, 35]])

In [5]:
np.sort(a)
np.sort(b,axis=1)

array([[11, 45, 60, 64],
       [ 8, 59, 65, 77],
       [23, 31, 67, 96],
       [18, 50, 80, 87],
       [33, 41, 57, 91],
       [35, 39, 65, 74]])

# np.append - the numpy.append() appends values along the mentioned axis at the end of the array

In [6]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [7]:
np.append(a,200)
np.append(a,[100,200,200])

array([ 27,  17,  97,  86,   4,  55,  49,  33,   3,  43,  10,  64,  16,
        50,  81, 100, 200, 200])

In [8]:
b

array([[64, 11, 45, 60],
       [65, 59,  8, 77],
       [96, 23, 31, 67],
       [87, 50, 18, 80],
       [57, 91, 33, 41],
       [65, 74, 39, 35]])

In [9]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[64., 11., 45., 60.,  1.],
       [65., 59.,  8., 77.,  1.],
       [96., 23., 31., 67.,  1.],
       [87., 50., 18., 80.,  1.],
       [57., 91., 33., 41.,  1.],
       [65., 74., 39., 35.,  1.]])

# np.concatenate - numpy.concatenate() function concatenate a sequence of array along an existing axis.

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique - we can get the unuque values from the the given array

In [12]:
e = np.array([1,2,2,2,3,3,3,3,4,4,4,5,5,5])
f = np.array([[1,2,3,3],[1,2,2,3]])
print(e)
print(f)

[1 2 2 2 3 3 3 3 4 4 4 5 5 5]
[[1 2 3 3]
 [1 2 2 3]]


In [13]:
np.unique(e)

array([1, 2, 3, 4, 5])

# np.expand_dims - we can get the expanded dimensions of array

In [14]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [15]:
a1 = np.expand_dims(a,axis=0)
a1
a2 = np.expand_dims(a,axis=1)
a2
b
b1 = np.expand_dims(b,axis=1)
b1

array([[[64, 11, 45, 60]],

       [[65, 59,  8, 77]],

       [[96, 23, 31, 67]],

       [[87, 50, 18, 80]],

       [[57, 91, 33, 41]],

       [[65, 74, 39, 35]]])

# np.where - The numpy.where() function return the indices of elements in an input array where given condition is satisfied.

In [16]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [17]:
# find all indicies with values greater then 50
np.where(a>50)


(array([ 2,  3,  5, 11, 14]),)

In [18]:
# Replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([27, 17,  0,  0,  4,  0, 49, 33,  3, 43, 10,  0, 16, 50,  0])

In [19]:
# find all indiecies with values even
np.where(a%2==0)

(array([ 3,  4, 10, 11, 12, 13]),)

In [20]:
np.where(a%2==0,0,a)

array([27, 17, 97,  0,  0, 55, 49, 33,  3, 43,  0,  0,  0,  0, 81])

# np.argmax - return indices of the max element of array in perticular axis.

In [22]:
print(a)
print(b)

[27 17 97 86  4 55 49 33  3 43 10 64 16 50 81]
[[64 11 45 60]
 [65 59  8 77]
 [96 23 31 67]
 [87 50 18 80]
 [57 91 33 41]
 [65 74 39 35]]


In [30]:
np.argmax(a)
np.argmax(b)
np.argmax(b,axis=0) # => axis = 0 means rows will getting changes cols are same
np.argmax(b,axis=1) # => axis = 1 means cols will getting changes rows are same


array([0, 3, 0, 0, 1, 1])

# np.argmin - return indices of the min element of array in perticular axis

In [33]:
np.argmin(a)
np.argmin(b,axis=0)
np.argmin(b,axis=1)

array([1, 2, 1, 2, 2, 3])

# np.cumsum - we want to compute the cumulative sum of array element over given axis.

In [34]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [43]:
np.cumsum(a)
np.cumsum(b,axis=0)
np.cumsum(b,axis=1)
np.cumsum(b)
np.cumprod(a)
np.cumprod(b,axis=0)
np.cumprod(b,axis=1)


array([[     64,     704,   31680, 1900800],
       [     65,    3835,   30680, 2362360],
       [     96,    2208,   68448, 4586016],
       [     87,    4350,   78300, 6264000],
       [     57,    5187,  171171, 7018011],
       [     65,    4810,  187590, 6565650]])

# np.percentile -

In [49]:
np.percentile(a,100)
np.percentile(a,0)
np.percentile(a,50)
np.median(a)


43.0

# np.histogram - frequency of data in graphical form.

In [50]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [53]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

# np.isin - one array having values are checked in a different numpy array having different elements with different size.

In [54]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [57]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False])

In [58]:
a[np.isin(a,items)]

array([10, 50])

# np.flip() :
the numpy.flip() function reverse the order of array elements along the specified axis. preserving the shape of the array.

In [61]:
a
b

array([[64, 11, 45, 60],
       [65, 59,  8, 77],
       [96, 23, 31, 67],
       [87, 50, 18, 80],
       [57, 91, 33, 41],
       [65, 74, 39, 35]])

In [60]:
np.flip(a)

array([81, 50, 16, 64, 10, 43,  3, 33, 49, 55,  4, 86, 97, 17, 27])

In [64]:
np.flip(b)
np.flip(b,axis=0)
np.flip(b,axis=1)

array([[60, 45, 11, 64],
       [77,  8, 59, 65],
       [67, 31, 23, 96],
       [80, 18, 50, 87],
       [41, 33, 91, 57],
       [35, 39, 74, 65]])

# np.put -
The numpy.put() function replace specific elements of an array with given values of p_array. Array indexes works on flattened array.

In [65]:
a

array([27, 17, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])

In [66]:
np.put(a,[0,1],[30,20])

In [67]:
a

array([30, 20, 97, 86,  4, 55, 49, 33,  3, 43, 10, 64, 16, 50, 81])