<a href="https://colab.research.google.com/github/nagarvishal/machine-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Create A One-D Array

a = np.array([1,2,3])
print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
#Create A Two-D Array
b = np.array([[1,2,3],[4,5,6]])
print(b,type(b))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [4]:
#Create A Three-D Array
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c,type(c))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]] <class 'numpy.ndarray'>


In [5]:
#Creating A Array of Specific dtype
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# np.arange
np.arange(1,11)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [7]:
# reshape of numpy array - np.arange(1,11).reshape(dim_outmost,rows,columns)
np.arange(1,11).reshape(2,5)
np.arange(1,13).reshape(1,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
# np.once and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# Generate the Random values Array - np.random
np.random.random((3,4))

array([[0.20758315, 0.47652183, 0.40039019, 0.03546724],
       [0.88048405, 0.75040357, 0.12202787, 0.43591054],
       [0.04289122, 0.13637252, 0.01494535, 0.11516793]])

In [11]:
# np.linspace()
np.linspace(-10,10,10)
# np.linspace(-10,10,10,dtype=int)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [13]:
# Array Attributes
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [14]:
# ndim - get the dimentions of numpy array
a1.ndim
a2.ndim
a3.ndim

3

In [15]:
# shape - get the shape of numpy array
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [16]:
# size -  get the number of items in numpy array
a1.size
a2.size
a3.size

8

In [17]:
# itemsize - get the size of numpy array element
a1.itemsize
a2.itemsize
a3.itemsize

8

In [18]:
# dtype - get the datatype of out numpy array element
a1.dtype
a2.dtype
a3.dtype

dtype('int64')

Changing DateType

In [19]:
# astype - Changing datatype of the numpy array
a4 = a3.astype(np.int32)
a4.dtype

dtype('int32')

Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
# Scalar Operations

#Airthmatic Operation
a1 * 2
a1 + 2
a1 - 2
a1 / 2
a1 ** 2
a1 % 2
a1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [22]:
#Relational Operation
a2 > 5
a2 < 5
a2 >= 5
a2 <= 5
a2 == 5
a2 != 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
# Vector Operations

# Airthmatic Operations
a1 + a2
a1 - a2
a1 * a2
a1 / a2
a1 // a2
a1 % a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Array Functions

In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[96., 68., 11.],
       [ 2., 57., 24.],
       [41., 75., 93.]])

In [25]:
# max,min,sum,prod -> 0=> col,1=>row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis=0)
np.max(a1,axis=1)
np.min(a1,axis=0)
np.min(a1,axis=1)
np.sum(a1,axis=0)
np.sum(a1,axis=1)
np.prod(a1,axis=0)
np.prod(a1,axis=1)


array([ 71808.,   2736., 285975.])

In [26]:
# mean,median,std,var
np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)
np.mean(a1,axis=0)
np.mean(a1,axis=1)
np.median(a1,axis=0)
np.median(a1,axis=1)
np.std(a1,axis=0)
np.std(a1,axis=1)
np.var(a1,axis=0)
np.var(a1,axis=1)

array([1250.88888889,  510.88888889,  464.88888889])

Trigonometric Functions

In [27]:
#Trigonometric Functions
np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[-5.45134011e+00, -2.04008160e+00, -2.25950846e+02],
       [-2.18503986e+00,  4.84699227e-01, -2.13489670e+00],
       [ 1.60656699e-01, -4.20700951e-01, -2.98738626e+00]])

DOT Product

In [28]:
# DOT Product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [29]:
# Log and Exponents
np.log(a1)
np.exp(a1)

array([[4.92345829e+41, 3.40427605e+29, 5.98741417e+04],
       [7.38905610e+00, 5.68572000e+24, 2.64891221e+10],
       [6.39843494e+17, 3.73324200e+32, 2.45124554e+40]])

In [30]:
# Rount,Floor,Ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[91., 11., 13.],
       [67., 89., 62.]])

Indexing And Slicing

In [31]:
# Indexing and Slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [32]:
#Indexing
print(a1[-1],a1[0])
print(a2[1,2],a2[2,3],a2[1,0])
print(a3[1,0,1],a3[0,0,0],a3[1,1,1])

9 0
6 11 4
5 0 7


In [33]:
#Slicing
a1
a1[2:5]
a1[2:5:2]

array([2, 4])

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3]);
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1,::3])
print(a2[0:2,1:])

[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [36]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
a3[1,:,:]
a3[2,1,0:]
a3[0:,0:,2:]
a3[0::2]
a3[0,1,:]
a3[1,:,1]
a3[2,1:,1:]
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [38]:
a1
a2
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
for i in a1:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [40]:
for i in a2:
    print(i,end=" ")

[0 1 2 3] [4 5 6 7] [ 8  9 10 11] 

In [41]:
for i in a3:
    print(i,end="\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [42]:
for i in np.nditer(a3):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [43]:

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Transpose

In [44]:
#Transpose
at = np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [45]:
#ravel - converting any dimentional array in one-d array
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [46]:
# Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [47]:
# Vertical Stacking
va1 = np.vstack((a4,a5,a4,a5))
va1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [48]:
# Horizontal Splitting
a4
hsa = np.hsplit(a4,2)
print(hsa[0])
print(hsa[1])

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [49]:
# Vertical Splitting
print(np.vsplit(a4,3))
np.vsplit(va1,4)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]