In [2]:
import numpy as np

In [3]:
a = np.array(4)

In [4]:
a

array(4)

In [5]:
a.ndim # here a is zero D tensore

0

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.ndim

1

In [8]:
arr.shape # (1D Tensor or Vector(4D) )

(5,)

##### 2D Tesnsor / Matrixs - 

In [10]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat.ndim

2

##### Example of 1D Tensors / Vector - 

array([[1],
       [2],
       [3]])

2