<a href="https://colab.research.google.com/github/nagarvishal/machine-learning/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# np.sort - return a sorted copy of an array

In [2]:
a = np.random.randint(1,100,15)
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b


array([[57, 47, 12, 24],
       [43, 87, 15,  4],
       [56, 91, 35, 46],
       [ 4, 11, 40, 61],
       [70, 62, 82, 53],
       [21, 66, 23, 82]])

In [4]:
np.sort(a)
np.sort(b,axis=1)

array([[12, 24, 47, 57],
       [ 4, 15, 43, 87],
       [35, 46, 56, 91],
       [ 4, 11, 40, 61],
       [53, 62, 70, 82],
       [21, 23, 66, 82]])

# np.append - the numpy.append() appends values along the mentioned axis at the end of the array

In [5]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [6]:
np.append(a,200)
np.append(a,[100,200,200])

array([  9,  19,  81,  37,  75,  81,  70,   4,  55,  90,   4,  67,  78,
        50,  97, 100, 200, 200])

In [7]:
b

array([[57, 47, 12, 24],
       [43, 87, 15,  4],
       [56, 91, 35, 46],
       [ 4, 11, 40, 61],
       [70, 62, 82, 53],
       [21, 66, 23, 82]])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[57., 47., 12., 24.,  1.],
       [43., 87., 15.,  4.,  1.],
       [56., 91., 35., 46.,  1.],
       [ 4., 11., 40., 61.,  1.],
       [70., 62., 82., 53.,  1.],
       [21., 66., 23., 82.,  1.]])

# np.concatenate - numpy.concatenate() function concatenate a sequence of array along an existing axis.

In [9]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis=0)
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique - we can get the unuque values from the the given array

In [11]:
e = np.array([1,2,2,2,3,3,3,3,4,4,4,5,5,5])
f = np.array([[1,2,3,3],[1,2,2,3]])
print(e)
print(f)

[1 2 2 2 3 3 3 3 4 4 4 5 5 5]
[[1 2 3 3]
 [1 2 2 3]]


In [12]:
np.unique(e)

array([1, 2, 3, 4, 5])

# np.expand_dims - we can get the expanded dimensions of array

In [13]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [14]:
a1 = np.expand_dims(a,axis=0)
a1
a2 = np.expand_dims(a,axis=1)
a2
b
b1 = np.expand_dims(b,axis=1)
b1

array([[[57, 47, 12, 24]],

       [[43, 87, 15,  4]],

       [[56, 91, 35, 46]],

       [[ 4, 11, 40, 61]],

       [[70, 62, 82, 53]],

       [[21, 66, 23, 82]]])

# np.where - The numpy.where() function return the indices of elements in an input array where given condition is satisfied.

In [15]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [16]:
# find all indicies with values greater then 50
np.where(a>50)


(array([ 2,  4,  5,  6,  8,  9, 11, 12, 14]),)

In [17]:
# Replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([ 9, 19,  0, 37,  0,  0,  0,  4,  0,  0,  4,  0,  0, 50,  0])

In [18]:
# find all indiecies with values even
np.where(a%2==0)

(array([ 6,  7,  9, 10, 12, 13]),)

In [19]:
np.where(a%2==0,0,a)

array([ 9, 19, 81, 37, 75, 81,  0,  0, 55,  0,  0, 67,  0,  0, 97])

# np.argmax - return indices of the max element of array in perticular axis.

In [20]:
print(a)
print(b)

[ 9 19 81 37 75 81 70  4 55 90  4 67 78 50 97]
[[57 47 12 24]
 [43 87 15  4]
 [56 91 35 46]
 [ 4 11 40 61]
 [70 62 82 53]
 [21 66 23 82]]


In [21]:
np.argmax(a)
np.argmax(b)
np.argmax(b,axis=0) # => axis = 0 means rows will getting changes cols are same
np.argmax(b,axis=1) # => axis = 1 means cols will getting changes rows are same


array([0, 1, 1, 3, 2, 3])

# np.argmin - return indices of the min element of array in perticular axis

In [22]:
np.argmin(a)
np.argmin(b,axis=0)
np.argmin(b,axis=1)

array([2, 3, 2, 0, 3, 0])

# np.cumsum - we want to compute the cumulative sum of array element over given axis.

In [23]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [24]:
np.cumsum(a)
np.cumsum(b,axis=0)
np.cumsum(b,axis=1)
np.cumsum(b)
np.cumprod(a)
np.cumprod(b,axis=0)
np.cumprod(b,axis=1)


array([[      57,     2679,    32148,   771552],
       [      43,     3741,    56115,   224460],
       [      56,     5096,   178360,  8204560],
       [       4,       44,     1760,   107360],
       [      70,     4340,   355880, 18861640],
       [      21,     1386,    31878,  2613996]])

# np.percentile -

In [25]:
np.percentile(a,100)
np.percentile(a,0)
np.percentile(a,50)
np.median(a)


67.0

# np.histogram - frequency of data in graphical form.

In [26]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [27]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

# np.isin - one array having values are checked in a different numpy array having different elements with different size.

In [28]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [29]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False,  True, False, False,
        True, False, False, False,  True, False])

In [30]:
a[np.isin(a,items)]

array([70, 90, 50])

# np.flip() :
the numpy.flip() function reverse the order of array elements along the specified axis. preserving the shape of the array.

In [31]:
a
b

array([[57, 47, 12, 24],
       [43, 87, 15,  4],
       [56, 91, 35, 46],
       [ 4, 11, 40, 61],
       [70, 62, 82, 53],
       [21, 66, 23, 82]])

In [32]:
np.flip(a)

array([97, 50, 78, 67,  4, 90, 55,  4, 70, 81, 75, 37, 81, 19,  9])

In [33]:
np.flip(b)
np.flip(b,axis=0)
np.flip(b,axis=1)

array([[24, 12, 47, 57],
       [ 4, 15, 87, 43],
       [46, 35, 91, 56],
       [61, 40, 11,  4],
       [53, 82, 62, 70],
       [82, 23, 66, 21]])

# np.put -
The numpy.put() function replace specific elements of an array with given values of p_array. Array indexes works on flattened array.

In [34]:
a

array([ 9, 19, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [35]:
np.put(a,[0,1],[30,20])

In [36]:
a

array([30, 20, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

# np.delete
The numpy.delete() function will return a new array with the deletion of sub-array along with the mention axis.

In [37]:
a

array([30, 20, 81, 37, 75, 81, 70,  4, 55, 90,  4, 67, 78, 50, 97])

In [38]:
np.delete(a,[0,1,2,3,4,5])

array([70,  4, 55, 90,  4, 67, 78, 50, 97])

In [39]:
b

array([[57, 47, 12, 24],
       [43, 87, 15,  4],
       [56, 91, 35, 46],
       [ 4, 11, 40, 61],
       [70, 62, 82, 53],
       [21, 66, 23, 82]])

In [40]:
np.delete(b,[0,1],axis=1)

array([[12, 24],
       [15,  4],
       [35, 46],
       [40, 61],
       [82, 53],
       [23, 82]])

In [41]:
np.delete(b,[0,1],axis=0)

array([[56, 91, 35, 46],
       [ 4, 11, 40, 61],
       [70, 62, 82, 53],
       [21, 66, 23, 82]])

# Set Functions


*   np.union1d
*   np.interset1d
*   np.setdiff1d
*   np.setxor1d
*   np.in1d




In [43]:
m = np.array([1,2,3,4,5,6])
n = np.array([4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
np.intersect1d(m,n)

array([4, 5, 6])

In [45]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [46]:
np.setxor1d(m,n)

array([1, 2, 3, 7])

In [47]:
np.in1d(m,n)

array([False, False, False,  True,  True,  True])